# Generated by Django 2.0.1 on 2018-09-24 13:43

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each uploaded file', primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('name', models.CharField(help_text='Enter a name for the file (less than 100 characters)', max_length=100, verbose_name='File Name')),
                ('file', models.FileField(upload_to=dashboard.models.user_upload_path, verbose_name='Uploaded File')),
                ('file_type', models.CharField(choices=[('v', 'Video'), ('t', 'Text'), ('o', 'Voice'), ('i', 'Image'), ('u', 'Unclassified')], default='u', max_length=1, verbose_name='File Type')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Upload Datetime')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('delete_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Datetime')),
                ('count_analyzed', models.IntegerField(default=0, verbose_name='Count of Analysis')),
                ('delete_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_by', to=settings.AUTH_USER_MODEL)),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_datetime'],
                'permissions': (('can_view_any_file', 'View Any File'), ('can_delete_any_file', 'Delete Any File')),
            },
        ),
        migrations.CreateModel(
            name='ImageMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for each file analysis record', primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('calc_status', models.CharField(choices=[('s', 'Success'), ('e', 'Error')], max_length=1, null=True, verbose_name='Analysis Status')),
                ('marked_image', models.FileField(null=True, upload_to=dashboard.models.marked_file_path, verbose_name='Marked Image')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Files')),
            ],
            options={
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='VideoMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for each file analysis record', primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('calc_status', models.CharField(choices=[('s', 'Success'), ('e', 'Error')], max_length=1, null=True, verbose_name='Analysis Status')),
                ('marked_video', models.FileField(null=True, upload_to=dashboard.models.marked_file_path, verbose_name='Marked Video')),
                ('frame_num', models.IntegerField(null=True, verbose_name='Number of Frames')),
                ('fps', models.FloatField(null=True, verbose_name='Frame per Second')),
                ('blink_count', models.IntegerField(help_text='Number of blinks in the video', null=True, verbose_name='Number of Blinks')),
                ('transcript', models.TextField(blank=True, help_text='Transcript of the speach in the video', max_length=10000, null=True, verbose_name='Video Transcript')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Files')),
            ],
            options={
                'ordering': ['-create_datetime'],
                'permissions': (('can_view_any_metric', 'View Any Metric'), ('can_edit_any_metric', 'Edit Any Metric')),
            },
        ),
    ]
