# Generated by Django 2.0.1 on 2018-10-04 13:14

import custom_storages
import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=custom_storages.PrivateMediaStorage(), upload_to=dashboard.models.user_upload_path, verbose_name='Uploaded File'),
        ),
        migrations.AlterField(
            model_name='videometrics',
            name='marked_video',
            field=models.FileField(null=True, storage=custom_storages.PrivateMediaStorage(), upload_to=dashboard.models.marked_file_path, verbose_name='Marked Video'),
        ),
    ]
